version: '3.8'

services:
  mongodb:
    image: mongo:6.0  # Usa la versión más reciente compatible
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: faketienda
    volumes:
      - mongodb_data:/data/db  # Persistencia de datos

volumes:
  mongodb_data:
    driver: local
